// Client-side views of the Bank Portal **underwrite-stage** API over the unified
// loan-request model (Phase 12 / Step 12.6), mirroring the backend wire DTOs of
// the Step 12.3 endpoints:
//   • `GET  /api/v1/bank/loan-requests?stage=underwrite` → List<LoanRequestRow>
//   • `POST /api/v1/bank/loan-requests/{id}/underwrite`   → UnderwritingReport
//   • `POST /api/v1/bank/loan-requests/{id}/decline`      → LoanRequestRow (echo)
//
// The underwrite queue lists only un-underwritten OPEN requests, so a row carries
// no verdict yet — the verdict/stamina/KPIs arrive with the report the
// `underwrite` POST returns. Approval is no longer an underwrite action (it is
// pricing, in the next tab); the only lifecycle action here is **decline**.

/// The system's predictive recommendation for a loan request (mirrors the backend
/// `Verdict` enum). Fixed by the §5.5 thresholds over stamina + forecast DTI:
/// `OK` (stamina≥70 & DTI≤34%), `BAD` (stamina≤48 | DTI≥71%), `WARN` otherwise.
/// Drives the report's headline verdict and the Price tab's risk hint.
enum Verdict {
  ok,
  warn,
  bad;

  /// Parse the upper-case wire value (`OK` | `WARN` | `BAD`); throws on anything
  /// else so a malformed payload surfaces as an error state, not a wrong badge.
  static Verdict fromWire(String value) => switch (value) {
    'OK' => Verdict.ok,
    'WARN' => Verdict.warn,
    'BAD' => Verdict.bad,
    _ => throw ArgumentError('Unknown verdict: $value'),
  };
}

/// One row of the underwrite-stage queue (`GET …/loan-requests?stage=underwrite`)
/// and the echo of `POST …/decline`. The queue lists un-underwritten OPEN
/// requests, so there is no verdict on the row — it is generated by the report.
/// [status] is `OPEN` in the queue and `DECLINED` on a decline echo.
class LoanRequestRow {
  const LoanRequestRow({
    required this.requestId,
    required this.applicantLabel,
    required this.initials,
    required this.amount,
    required this.purpose,
    required this.status,
  });

  final String requestId;

  /// The client's display label (name).
  final String applicantLabel;

  /// Up-to-two-letter avatar initials.
  final String initials;

  /// Requested financing amount (SAR), raw `numeric(14,2)` from the API.
  final double amount;

  /// The stated loan purpose, or null when none was captured.
  final String? purpose;

  /// Request lifecycle status (`OPEN` in the queue; `DECLINED` after a decline).
  final String status;

  factory LoanRequestRow.fromJson(Map<String, dynamic> json) {
    return LoanRequestRow(
      requestId: json['requestId'] as String,
      applicantLabel: json['applicantLabel'] as String,
      initials: json['initials'] as String,
      amount: (json['amount'] as num).toDouble(),
      purpose: json['purpose'] as String?,
      status: json['status'] as String,
    );
  }
}

/// One month-end point on the report's 12-month cash-flow chart: the projected
/// month-end [balance] on [date] (reuses the consumer forecast chart's shape).
class CashFlowPoint {
  const CashFlowPoint({required this.date, required this.balance});

  final DateTime date;
  final double balance;

  factory CashFlowPoint.fromJson(Map<String, dynamic> json) {
    return CashFlowPoint(
      date: DateTime.parse(json['date'] as String),
      balance: (json['balance'] as num).toDouble(),
    );
  }
}

/// A full predictive underwriting report (`POST …/loan-requests/{id}/underwrite`,
/// DESIGN §5.5/§7.5): the verdict panel, the stamina box, the three KPI boxes
/// (forecast DTI, income stability, 12-month default probability) and the
/// 12-month cash-flow chart. The three ratio metrics are already percentages
/// (server-computed). The payload also carries the compliance surface
/// (tokenized accounts, residency marker) — not shown in this pane, so ignored.
class UnderwritingReport {
  const UnderwritingReport({
    required this.applicationId,
    required this.applicantName,
    required this.initials,
    required this.purpose,
    required this.amount,
    required this.staminaScore,
    required this.forecastDti,
    required this.incomeStability,
    required this.defaultProb12mo,
    required this.verdict,
    required this.riskTier,
    required this.cashFlow,
  });

  final String applicationId;
  final String applicantName;
  final String initials;
  final String purpose;
  final double amount;

  /// Long-term cash-flow endurance, 0–100 (higher = stronger).
  final int staminaScore;

  /// Forecast debt-to-income after the requested loan, as a percentage.
  final double forecastDti;

  /// Income regularity, as a percentage (100 = perfectly steady).
  final double incomeStability;

  /// Modelled 12-month probability of default, as a percentage.
  final double defaultProb12mo;

  final Verdict verdict;
  final String riskTier;

  /// The 12-month projected month-end balance series driving the report chart.
  final List<CashFlowPoint> cashFlow;

  factory UnderwritingReport.fromJson(Map<String, dynamic> json) {
    return UnderwritingReport(
      applicationId: json['applicationId'] as String,
      applicantName: json['applicantName'] as String,
      initials: json['initials'] as String,
      purpose: json['purpose'] as String,
      amount: (json['amount'] as num).toDouble(),
      staminaScore: (json['staminaScore'] as num).toInt(),
      forecastDti: (json['forecastDti'] as num).toDouble(),
      incomeStability: (json['incomeStability'] as num).toDouble(),
      defaultProb12mo: (json['defaultProb12mo'] as num).toDouble(),
      verdict: Verdict.fromWire(json['verdict'] as String),
      riskTier: json['riskTier'] as String,
      cashFlow: (json['cashFlow'] as List<dynamic>)
          .map((e) => CashFlowPoint.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }
}
