spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/baseerah
    username: baseerah
    password: baseerah
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
